#!/usr/bin/ruby

require 'rubygems'
require 'mechanize'
require 'hpricot'
require 'json'

$username = ARGV[0]
$password = ARGV[1]

$login_url = "https://store.playstation.com/external/index.vm?returnURL=https%3a%2f%2fsecureus.playstation.com%2fRegistration%2fPSNL%2fSignInFrame.aspx"
$friend_url = "http://profiles.us.playstation.com/playstation/psn/profile/friends"
$json_url = "http://profiles.us.playstation.com/playstation/psn/profile/get_gamer_summary_data?id="

def get_agent()
    agent = WWW::Mechanize.new
    agent.user_agent_alias = 'Mac FireFox'
    agent.redirect_ok = true
 
    page = agent.get($login_url)
    login_form = page.forms.first
    login_form.loginName = $username
    login_form.password = $password
    page = agent.submit(login_form)
    link = page.links.first

    if link.text == "Sign In"
        puts "Error logging in. Did you give the right username and password?"
        exit
    end

    page = link.click
   
    return agent
end

def get_friends(agent)
    page = agent.get($friend_url)
    body = Hpricot.parse(page.body)
    divs = body.search("div.slotcontent")

    friends = []
    for div in divs
        friends << div.attributes["id"]
    end

    return friends
end 

def get_friend_status(agent, friend)
    page = agent.get($json_url + friend)
    data = JSON.parse(page.body)

    friend = {:name => data["userName"]}

    if data["onlineStatus"]["extensionStatus"] != nil
       friend[:status] = 'online'
       friend[:playing] = data["onlineStatus"]["extensionStatus"]["title"]
    else
       friend[:status] = 'offline'
       friend[:playing] = ""
    end

    return friend
end

agent = get_agent()
friend_names = get_friends(agent)

for friend_name in friend_names
    friend = get_friend_status(agent, friend_name)

    puts friend[:status] + "\t" + friend[:name] + "\t" + friend[:playing]
end
